/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC165Contract } from "./ERC165";
import { ERC721Contract } from "./ERC721";
import { ERC721ConnectorContract } from "./ERC721Connector";
import { ERC721EnumerableContract } from "./ERC721Enumerable";
import { ERC721MetadataContract } from "./ERC721Metadata";
import { IERC165Contract } from "./IERC165";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { MigrationsContract } from "./Migrations";
import { NftMarketplaceContractContract } from "./NftMarketplaceContract";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721Connector"): ERC721ConnectorContract;
      require(name: "ERC721Enumerable"): ERC721EnumerableContract;
      require(name: "ERC721Metadata"): ERC721MetadataContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "NftMarketplaceContract"): NftMarketplaceContractContract;
    }
  }
}

export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721ConnectorContract,
  ERC721ConnectorInstance,
} from "./ERC721Connector";
export {
  ERC721EnumerableContract,
  ERC721EnumerableInstance,
} from "./ERC721Enumerable";
export {
  ERC721MetadataContract,
  ERC721MetadataInstance,
} from "./ERC721Metadata";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  NftMarketplaceContractContract,
  NftMarketplaceContractInstance,
} from "./NftMarketplaceContract";
